### ISSUE TITLE
Exception for SmartIndexRandomizer

### ISSUE THREAD

**Issue by renamed** [renamed/WiSARD#2]
Message: System.ArgumentException : Source array was not long enough. Check srcIndex and length, and the array's lower bounds.

```
Test Name:	WiSARD.Tests.Mnist.Test1
Test FullName:	WiSARD.Tests.Mnist.Test1
Test Source:	C:\Users\Renato\Documents\GitHub\JWiSARD\WiSARD\WiSARD.Tests\Mnist.cs : line 15
Test Outcome:	Failed
Test Duration:	0:00:00,046

Result StackTrace:	
at System.Array.Copy(Array sourceArray, Int32 sourceIndex, Array destinationArray, Int32 destinationIndex, Int32 length, Boolean reliable)
   at System.Array.Copy(Array sourceArray, Array destinationArray, Int32 length)
   at WiSARD.IndexHandler.SmartIndexRandomizer.DoRaffle(Int32 matrixSize, Int32 linkageNumber) in C:\Users\Renato\Documents\GitHub\JWiSARD\WiSARD\WiSARD\IndexHandler\SmartIndexRandomizer.cs:line 59
   at WiSARD.IndexHandler.SmartIndexRandomizer..ctor(Int32 matrixSize, Int32 linkageNumber) in C:\Users\Renato\Documents\GitHub\JWiSARD\WiSARD\WiSARD\IndexHandler\SmartIndexRandomizer.cs:line 32
   at WiSARD.Tests.Mnist.Test1() in C:\Users\Renato\Documents\GitHub\JWiSARD\WiSARD\WiSARD.Tests\Mnist.cs:line 21
Result Message:	System.ArgumentException : Source array was not long enough. Check srcIndex and length, and the array's lower bounds.
```

**Comment by renamed** [comment]
System.Array.Copy expects the 3rd parameter to be the length of the source array to copy. We were passing the total length to be copied.
